apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mastery-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "invoicing.master.srrdevcloud.in"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mastery-virtualservice
spec:
  hosts:
  - "invoicing.master.srrdevcloud.in"
  gateways:
  - mastery-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: invpricing-poc-service
